apiVersion: v1
kind: Service
metadata:
  name: nexus-api
  labels:
    app: nexus-api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: nexus-api
