apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-api
  labels:
    app: nexus-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: nexus-api
  template:
    metadata:
      labels:
        app: nexus-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: nexus-config
            - secretRef:
                name: nexus-secrets
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
