apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: nexus-migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: "{{ .Values.api.image.repository }}:{{ .Values.global.imageTag }}"
          command: ["pnpm", "dlx", "prisma", "migrate", "deploy"]
          envFrom:
            - configMapRef:
                name: nexus-config
            - secretRef:
                name: nexus-secrets
