apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-web
  labels:
    app: nexus-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: nexus-web
  template:
    metadata:
      labels:
        app: nexus-web
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nexus-config
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
